development:
  host: "127.0.0.1"
  port: 9042
  keyspace: zentry_development
  max_retries: 3
  retry_delay: 0.5

test:
  host: "127.0.0.1"
  port: 9042
  keyspace: zentry_test
  max_retries: 3
  retry_delay: 0.5

production:
  hosts:
    - "cassandra-1.example.com"
    - "cassandra-2.example.com"
  port: 9042
  keyspace: zentry_production
  username: '<%= ENV["CASSANDRA_USERNAME"] %>'
  password: '<%= ENV["CASSANDRA_PASSWORD"] %>'
  max_retries: 3
  retry_delay: 0.5
