default: &default
  brokers:
    - <%= ENV.fetch('KAFKA_BROKER', 'kafka:9092') %>
  client_id: zentry
  connect_timeout: 10
  socket_timeout: 30

  # Consumer specific settings
  consumer:
    group_id: <%= ENV.fetch('KAFKA_CONSUMER_GROUP_ID', 'zentry_consumer') %>
    session_timeout: <%= ENV.fetch('KAFKA_SESSION_TIMEOUT', 30) %> # 30 seconds
    offset_retention_time: <%= ENV.fetch('KAFKA_OFFSET_RETENTION_TIME', 86400) %> # 24 hours
    heartbeat_interval: <%= ENV.fetch('KAFKA_HEARTBEAT_INTERVAL', 10) %> # 10 seconds

  # Producer specific settings
  producer:
    ack_timeout: <%= ENV.fetch('KAFKA_ACK_TIMEOUT', 5) %> # 5 seconds
    required_acks: <%= ENV.fetch('KAFKA_REQUIRED_ACKS', 1) %> # Wait for the leader to acknowledge
    max_buffer_size: <%= ENV.fetch('KAFKA_MAX_BUFFER_SIZE', 10000) %> # Number of messages
    max_buffer_bytesize: <%= ENV.fetch('KAFKA_MAX_BUFFER_BYTESIZE', 10485760) %> # 10MB
    compression_codec: <%= ENV.fetch('KAFKA_COMPRESSION_CODEC', 'gzip') %> # snappy, gzip, or nil
    compression_threshold: <%= ENV.fetch('KAFKA_COMPRESSION_THRESHOLD', 1024) %> # 1KB

  topics:
    sleep_entries: <%= ENV.fetch('KAFKA_TOPIC_SLEEP_ENTRIES', 'sleep_entries') %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
